volumes:
  data_dir:
  wordpress:

networks:
  wordpress_net:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - data_dir:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    container_name: wordpress
    build: ./wordpress
    restart: always
    environment:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_HOST: ${DB_HOST}
        DB_PASSWORD: ${DB_PASSWORD}
        WD_TITLE: ${WD_TITLE}
        WD_USER: ${WD_USER}
        WD_PASSWORD: ${WD_PASSWORD}
        WD_NAME: ${WD_NAME}
        WD_EMAIL: ${WD_EMAIL}
        WD_HOST: ${WD_HOST}
        WD_USER_ADMIN: ${WD_USER_ADMIN}
        WD_EMAIL_ADMIN: ${WD_EMAIL_ADMIN}
        WD_PASSWORD_ADMIN: ${WD_PASSWORD_ADMIN}
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    restart: unless-stopped