volumes:
  data_dir:
  wordpress:

networks:
  wordpress_net:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - data_dir:/var/lib/DB
    networks:
      - wordpress_net

  wordpress:
    container_name: wordpress
    build: ./wordpress
    restart: always
    environment:
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_net
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    restart: unless-stopped