volumes:
  data_dir:
  wordpress:

networks:
  wordpress_net:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
    volumes:
      - data_dir:/var/lib/mysql
      - ../secrets/general:/etc/security
    networks:
      - wordpress_net

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    environment:
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DOMAIN_NAME: ${DOMAIN_NAME}
        WD_TITLE: ${WD_TITLE}
    volumes:
      - wordpress:/var/www/html
      - ../secrets/general:/etc/security
    networks:
      - wordpress_net
    depends_on:
      - mariadb
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ../secrets/certs:/etc/nginx/certs:ro
    networks:
      - wordpress_net
    depends_on:
      - wordpress
    restart: unless-stopped